version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "bank"
      POSTGRES_USER: "bank"
      POSTGRES_PASSWORD: "bank"
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d